version: '2'
services:
  poconetimepayment-app:
    image: poconetimepayment
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://poconetimepayment-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=pocOneTimePayment
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8087:8087
  poconetimepayment-mongodb:
    extends:
      file: mongodb.yml
      service: poconetimepayment-mongodb
